{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "90cd5112",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[33mWARNING: The directory '/home/jovyan/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: numpy in /opt/conda/lib/python3.7/site-packages (1.21.6)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: The directory '/home/jovyan/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.\u001b[0m\u001b[33m\n",
      "\u001b[0mCollecting pyopenms\n",
      "  Downloading pyopenms-2.7.0-cp37-cp37m-manylinux2014_x86_64.whl (49.0 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m49.0/49.0 MB\u001b[0m \u001b[31m6.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n",
      "\u001b[?25hRequirement already satisfied: numpy in /opt/conda/lib/python3.7/site-packages (from pyopenms) (1.21.6)\n",
      "Installing collected packages: pyopenms\n",
      "Successfully installed pyopenms-2.7.0\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: The directory '/home/jovyan/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.\u001b[0m\u001b[33m\n",
      "\u001b[0mCollecting biopython\n",
      "  Downloading biopython-1.81-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m3.0/3.0 MB\u001b[0m \u001b[31m7.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hRequirement already satisfied: numpy in /opt/conda/lib/python3.7/site-packages (from biopython) (1.21.6)\n",
      "Installing collected packages: biopython\n",
      "Successfully installed biopython-1.81\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: The directory '/home/jovyan/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.\u001b[0m\u001b[33m\n",
      "\u001b[0mCollecting openpyxl\n",
      "  Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m250.0/250.0 kB\u001b[0m \u001b[31m1.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hCollecting et-xmlfile\n",
      "  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)\n",
      "Installing collected packages: et-xmlfile, openpyxl\n",
      "Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.2\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "# ### basic required packages ###\n",
    "!pip install numpy\n",
    "!pip install pyopenms\n",
    "!pip install biopython\n",
    "!pip install openpyxl"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "13a2f1a6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[33mWARNING: The directory '/home/jovyan/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.\u001b[0m\u001b[33m\n",
      "\u001b[0mCollecting google-api-python-client\n",
      "  Downloading google_api_python_client-2.103.0-py2.py3-none-any.whl (12.6 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m12.6/12.6 MB\u001b[0m \u001b[31m56.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hCollecting google-auth-httplib2\n",
      "  Downloading google_auth_httplib2-0.1.1-py2.py3-none-any.whl (9.3 kB)\n",
      "Collecting google-auth-oauthlib\n",
      "  Downloading google_auth_oauthlib-1.1.0-py2.py3-none-any.whl (19 kB)\n",
      "Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5\n",
      "  Downloading google_api_core-2.12.0-py3-none-any.whl (121 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m121.4/121.4 kB\u001b[0m \u001b[31m204.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hCollecting uritemplate<5,>=3.0.1\n",
      "  Downloading uritemplate-4.1.1-py2.py3-none-any.whl (10 kB)\n",
      "Collecting google-auth<3.0.0.dev0,>=1.19.0\n",
      "  Downloading google_auth-2.23.3-py2.py3-none-any.whl (182 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m182.3/182.3 kB\u001b[0m \u001b[31m200.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hCollecting httplib2<1.dev0,>=0.15.0\n",
      "  Downloading httplib2-0.22.0-py3-none-any.whl (96 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m96.9/96.9 kB\u001b[0m \u001b[31m98.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hCollecting requests-oauthlib>=0.7.0\n",
      "  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)\n",
      "Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5 in /opt/conda/lib/python3.7/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (4.21.7)\n",
      "Collecting googleapis-common-protos<2.0.dev0,>=1.56.2\n",
      "  Downloading googleapis_common_protos-1.61.0-py2.py3-none-any.whl (230 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m230.9/230.9 kB\u001b[0m \u001b[31m113.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hRequirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in /opt/conda/lib/python3.7/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2.28.1)\n",
      "Collecting rsa<5,>=3.1.4\n",
      "  Downloading rsa-4.9-py3-none-any.whl (34 kB)\n",
      "Collecting pyasn1-modules>=0.2.1\n",
      "  Downloading pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m181.3/181.3 kB\u001b[0m \u001b[31m157.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hCollecting cachetools<6.0,>=2.0.0\n",
      "  Downloading cachetools-5.3.1-py3-none-any.whl (9.3 kB)\n",
      "Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /opt/conda/lib/python3.7/site-packages (from httplib2<1.dev0,>=0.15.0->google-api-python-client) (3.0.9)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /opt/conda/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.2.1)\n",
      "Collecting pyasn1<0.6.0,>=0.4.6\n",
      "  Downloading pyasn1-0.5.0-py2.py3-none-any.whl (83 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m83.9/83.9 kB\u001b[0m \u001b[31m127.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hRequirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (3.4)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in /opt/conda/lib/python3.7/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2.1.1)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2022.9.24)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (1.26.11)\n",
      "Installing collected packages: uritemplate, pyasn1, httplib2, googleapis-common-protos, cachetools, rsa, requests-oauthlib, pyasn1-modules, google-auth, google-auth-oauthlib, google-auth-httplib2, google-api-core, google-api-python-client\n",
      "Successfully installed cachetools-5.3.1 google-api-core-2.12.0 google-api-python-client-2.103.0 google-auth-2.23.3 google-auth-httplib2-0.1.1 google-auth-oauthlib-1.1.0 googleapis-common-protos-1.61.0 httplib2-0.22.0 pyasn1-0.5.0 pyasn1-modules-0.3.0 requests-oauthlib-1.3.1 rsa-4.9 uritemplate-4.1.1\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: The directory '/home/jovyan/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.\u001b[0m\u001b[33m\n",
      "\u001b[0mCollecting oauth2client\n",
      "  Downloading oauth2client-4.1.3-py2.py3-none-any.whl (98 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m98.2/98.2 kB\u001b[0m \u001b[31m1.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hRequirement already satisfied: rsa>=3.1.4 in /opt/conda/lib/python3.7/site-packages (from oauth2client) (4.9)\n",
      "Requirement already satisfied: pyasn1>=0.1.7 in /opt/conda/lib/python3.7/site-packages (from oauth2client) (0.5.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.0.5 in /opt/conda/lib/python3.7/site-packages (from oauth2client) (0.3.0)\n",
      "Requirement already satisfied: httplib2>=0.9.1 in /opt/conda/lib/python3.7/site-packages (from oauth2client) (0.22.0)\n",
      "Requirement already satisfied: six>=1.6.1 in /opt/conda/lib/python3.7/site-packages (from oauth2client) (1.16.0)\n",
      "Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /opt/conda/lib/python3.7/site-packages (from httplib2>=0.9.1->oauth2client) (3.0.9)\n",
      "Installing collected packages: oauth2client\n",
      "Successfully installed oauth2client-4.1.3\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: The directory '/home/jovyan/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: oauth2client in /opt/conda/lib/python3.7/site-packages (4.1.3)\n",
      "Requirement already satisfied: pyasn1>=0.1.7 in /opt/conda/lib/python3.7/site-packages (from oauth2client) (0.5.0)\n",
      "Requirement already satisfied: httplib2>=0.9.1 in /opt/conda/lib/python3.7/site-packages (from oauth2client) (0.22.0)\n",
      "Requirement already satisfied: rsa>=3.1.4 in /opt/conda/lib/python3.7/site-packages (from oauth2client) (4.9)\n",
      "Requirement already satisfied: pyasn1-modules>=0.0.5 in /opt/conda/lib/python3.7/site-packages (from oauth2client) (0.3.0)\n",
      "Requirement already satisfied: six>=1.6.1 in /opt/conda/lib/python3.7/site-packages (from oauth2client) (1.16.0)\n",
      "Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /opt/conda/lib/python3.7/site-packages (from httplib2>=0.9.1->oauth2client) (3.0.9)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "# ### GOOGLE AUTH ###\n",
    "!pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib\n",
    "!pip3 install --upgrade oauth2client \n",
    "!pip3 install --upgrade oauth2client "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "4261d98e",
   "metadata": {},
   "outputs": [],
   "source": [
    "#######################\n",
    "###  Запускать тут ####\n",
    "#######################\n",
    "\n",
    "import glob\n",
    "import pandas as pd\n",
    "import os\n",
    "\n",
    "# # CHANGE THIS\n",
    "# EXPERIMENT_NAME = \"KJE0006\"\n",
    "\n",
    "# Список для хранения обработанных DataFrame из каждого файла\n",
    "\n",
    "\n",
    "def xlsx_paths(EXPERIMENT_NAME):\n",
    "    # specifying the path to csv files\n",
    "    path = f\"./requests/{EXPERIMENT_NAME}\"\n",
    "\n",
    "    # csv files in the path\n",
    "    file_paths = glob.glob(path + \"/*.xlsx\")\n",
    "    return file_paths\n",
    "\n",
    "def csv_paths(EXPERIMENT_NAME):\n",
    "    # specifying the path to csv files\n",
    "    path = f\"./requests/{EXPERIMENT_NAME}\"\n",
    "\n",
    "    # csv files in the path\n",
    "    file_paths = glob.glob(path + \"/*.csv\")\n",
    "    return file_paths\n",
    "\n",
    "def is_valid_sequence(seq):\n",
    "\n",
    "    if pd.isna(seq):\n",
    "        return False\n",
    "    valid_chars = set(\"ATGCUYRSWKMBDHVN.-\")\n",
    "    return all(c in valid_chars for c in str(seq))\n",
    "\n",
    "def process_excel_files(xlsx_paths, dfs_list):\n",
    "\n",
    "    for file_path in xlsx_paths:\n",
    "        # Чтение файла Excel\n",
    "        df = pd.read_excel(file_path, header=None)\n",
    "        \n",
    "        if len(df.columns)==1:\n",
    "            df = df[0].str.split(',', expand=True)\n",
    "\n",
    "        if len(df.columns)<4:\n",
    "            return print(\"ERROR IN INPUT FILE\")\n",
    "        df.dropna(how='any', inplace=True)\n",
    "        \n",
    "        # df curation\n",
    "        for column in df.columns:\n",
    "            df[column] = df[column].apply(lambda x: unicodedata.normalize('NFC', str(x)))\n",
    "        #  pandas' Series.str.strip() method\n",
    "        df = df.apply(lambda x: x.str.strip())\n",
    "        \n",
    "        df[0] = df[0].apply(lambda x: x.upper())\n",
    "\n",
    "        # Получение имени самого левого столбца\n",
    "        leftmost_column = df.columns[0]\n",
    "        print(file_path, len(df))\n",
    "        # Фильтрация строк согласно заданным условиям\n",
    "        df = df[df[leftmost_column].apply(is_valid_sequence)]\n",
    "        \n",
    "        print(file_path, len(df))\n",
    "        # Добавление обработанного DataFrame в список\n",
    "        dfs_list.append(df)\n",
    "        \n",
    "        if dfs_list != None:\n",
    "            pass\n",
    "        else:\n",
    "            dfs_list = []\n",
    "            print([])\n",
    "        \n",
    "    return dfs_list\n",
    "        \n",
    "    \n",
    "def process_csv_files(csv_paths, dfs_list):\n",
    "\n",
    "    for file_path in csv_paths:\n",
    "        # Чтение файла Excel\n",
    "        df = pd.read_csv(file_path, header=None, sep=\",\")\n",
    "        print(df)\n",
    "        df.dropna(how='any', inplace=True)\n",
    "        if len(df.columns)==1:\n",
    "            df = df[0].str.split(',', expand=True)\n",
    "\n",
    "        if len(df.columns)<4:\n",
    "            return print(\"ERROR IN INPUT FILE\")\n",
    "\n",
    "        # df curation\n",
    "        for column in df.columns:\n",
    "            df[column] = df[column].apply(lambda x: unicodedata.normalize('NFC', str(x)))\n",
    "        #  pandas' Series.str.strip() method\n",
    "        df = df.apply(lambda x: x.str.strip())\n",
    "        \n",
    "        df[0] = df[0].apply(lambda x: x.upper())\n",
    "\n",
    "        # Получение имени самого левого столбца\n",
    "        leftmost_column = df.columns[0]\n",
    "        print(file_path, len(df))\n",
    "        # Фильтрация строк согласно заданным условиям\n",
    "        df = df[df[leftmost_column].apply(is_valid_sequence)]\n",
    "        \n",
    "        # Добавление обработанного DataFrame в список\n",
    "        dfs_list.append(df)\n",
    "        \n",
    "        if dfs_list != None:\n",
    "            pass\n",
    "        else:\n",
    "            dfs_list = []\n",
    "            print([])\n",
    "            \n",
    "    return dfs_list\n",
    "        \n",
    "def process_files(EXPERIMENT_NAME):\n",
    "    dfs_list = []\n",
    "    dfs_list = process_excel_files(xlsx_paths(EXPERIMENT_NAME), dfs_list)\n",
    "    if dfs_list != None:\n",
    "        print(dfs_list)\n",
    "    else:\n",
    "        dfs_list = []\n",
    "    dfs_list = process_csv_files(csv_paths(EXPERIMENT_NAME), dfs_list)\n",
    "    return dfs_list\n",
    "\n",
    "# EXPERIMENT_NAME = input()\n",
    "# dfs_list=process_files(EXPERIMENT_NAME)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "c17cbdd8",
   "metadata": {},
   "outputs": [],
   "source": [
    "# # process_excel_files(xlsx_paths(EXPERIMENT_NAME), dfs_list)\n",
    "# from google.colab import data_table\n",
    "# data_table.enable_dataframe_formatter()\n",
    "\n",
    "# from IPython.display import display\n",
    "\n",
    "# # print the DataFrame\n",
    "# display(dfs_list[-2][10:])\n",
    "\n",
    "# Nikiteev_df=dfs_list[-2]\n",
    "\n",
    "# Nikiteev_df=Nikiteev_df.dropna(how='any', inplace=True)\n",
    "\n",
    "# display(Nikiteev_df[10:59])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "4a024e3f",
   "metadata": {},
   "outputs": [],
   "source": [
    "def export_to_input_files(dfs_list, EXPERIMENT_NAME):\n",
    "    # Конкатенация всех обработанных DataFrame по строкам\n",
    "    final_df = None\n",
    "    final_df = pd.concat(dfs_list, axis=0, join='outer', ignore_index=True)\n",
    "    if (len(final_df)>384 and len(final_df)<=768):\n",
    "\n",
    "        df_A = final_df[:384]\n",
    "        df_B = final_df[384:]\n",
    "\n",
    "        # Сохранение результата в новый файл CSV\n",
    "        df_A.to_csv(f\"./result_input/{EXPERIMENT_NAME}_concatenated_file_plate_A.csv\", index=False, sep = ',', header = None, encoding = \"UTF-8\")\n",
    "        # Сохранение результата в новый файл Excel\n",
    "        df_A.to_excel(f\"./result_input/{EXPERIMENT_NAME}_concatenated_file_plate_A.xlsx\", index=False, header = None, encoding = \"UTF-8\")\n",
    "\n",
    "         # Сохранение результата в новый файл CSV\n",
    "        df_B.to_csv(f\"./result_input/{EXPERIMENT_NAME}_concatenated_file_plate_B.csv\", index=False, sep = ',', header = None, encoding = \"UTF-8\")\n",
    "        # Сохранение результата в новый файл Excel\n",
    "        df_B.to_excel(f\"./result_input/{EXPERIMENT_NAME}_concatenated_file_plate_B.xlsx\", index=False, header = None, encoding = \"UTF-8\")\n",
    "\n",
    "    elif len(final_df)>768:\n",
    "    \n",
    "        print(\"error, too much oligos HALP\")\n",
    "    \n",
    "    else:\n",
    "\n",
    "        # Сохранение результата в новый файл CSV\n",
    "        final_df.to_csv(f\"./result_input/{EXPERIMENT_NAME}_concatenated_file.csv\", index=False, sep = ',', header = None, encoding = \"UTF-8\")\n",
    "\n",
    "        # Сохранение результата в новый файл Excel\n",
    "        final_df.to_excel(f\"./result_input/{EXPERIMENT_NAME}_concatenated_file.xlsx\", index=False, header = None, encoding = \"UTF-8\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "c8710862",
   "metadata": {},
   "outputs": [],
   "source": [
    "#!/usr/bin/env python\n",
    "#\n",
    "# File: DrOligoInputPreparation_withFormsAPI.py\n",
    "# Author: Oleg Fedorov, Kamil Zaynullin\n",
    "#\n",
    "# Copyright (C) 2023 Group of automated synthesis\n",
    "#\n",
    "# This file is part of gene synthesis automatization pipeline implemented in SBM.\n",
    "\n",
    "from __future__ import print_function\n",
    "\n",
    "import io\n",
    "import os\n",
    "\n",
    "########################\n",
    "## GOOGLE API IMPORTS ##\n",
    "########################\n",
    "from apiclient import discovery\n",
    "from google.oauth2.credentials import Credentials\n",
    "from googleapiclient.errors import HttpError\n",
    "from googleapiclient.http import MediaIoBaseDownload\n",
    "from httplib2 import Http\n",
    "from oauth2client import client, file, tools\n",
    "\n",
    "SCOPES = \"https://www.googleapis.com/auth/drive\"\n",
    "DISCOVERY_DOC = \"https://forms.googleapis.com/$discovery/rest?version=v1\"\n",
    "\n",
    "\n",
    "def creating_dirs(EXPERIMENT_NAME):\n",
    "    #################\n",
    "    ## CREATE DIR  ##\n",
    "    #################\n",
    "    cwd = os.getcwd()\n",
    "    dir = os.path.join(cwd, \"requests\", EXPERIMENT_NAME)\n",
    "    if not os.path.exists(dir):\n",
    "        os.mkdir(dir)\n",
    "\n",
    "\n",
    "def google_auth():\n",
    "    #################\n",
    "    ## GOOGLE AUTH ##\n",
    "    #################\n",
    "\n",
    "    \"\"\"\n",
    "    caution! it appeares to be deprecated!!!\n",
    "\n",
    "    \"\"\"\n",
    "    cwd = os.getcwd()\n",
    "    token_file = os.path.join(cwd, \"token.json\")\n",
    "    if os.path.exists(token_file):\n",
    "        print(\"auth token already exists\")\n",
    "        store = file.Storage(token_file)\n",
    "        creds = store.get()\n",
    "    else:\n",
    "        store = file.Storage(\"token.json\")\n",
    "        creds = None\n",
    "        if not creds:\n",
    "            flow = client.flow_from_clientsecrets(\"credentials.json\", SCOPES)\n",
    "\n",
    "            creds = tools.run_flow(flow, store)\n",
    "    return creds\n",
    "\n",
    "\n",
    "def retrive_forms_data(creds):\n",
    "    ##################\n",
    "    ## GOOGLE FORMS ##\n",
    "    ##################\n",
    "    service = discovery.build(\n",
    "        \"forms\",\n",
    "        \"v1\",\n",
    "        http=creds.authorize(Http()),\n",
    "        discoveryServiceUrl=DISCOVERY_DOC,\n",
    "        static_discovery=False,\n",
    "    )\n",
    "\n",
    "    form_id = \"1bVGyD-pz5w3BXM48yHWnhEDVnYNVgzRrF3ysvjAbqHQ\"\n",
    "    result = service.forms().responses().list(formId=form_id).execute()\n",
    "    file_list = [\n",
    "        response[\"answers\"][\"778e4a4f\"][\"fileUploadAnswers\"][\"answers\"]\n",
    "        for response in result[\"responses\"]\n",
    "    ]\n",
    "    print(file_list)\n",
    "    return file_list\n",
    "\n",
    "\n",
    "####################################################\n",
    "# downloading from Google Disk and writing to file #\n",
    "####################################################\n",
    "def download_request_file(fileID, filename, creds, EXPERIMENT_NAME):\n",
    "    try:\n",
    "        service = discovery.build(\"drive\", \"v3\", credentials=creds)\n",
    "\n",
    "        file_id = fileID\n",
    "\n",
    "        # pylint: disable=maybe-no-member\n",
    "        request = service.files().get_media(fileId=file_id)\n",
    "        file = io.BytesIO()\n",
    "        downloader = MediaIoBaseDownload(file, request)\n",
    "        done = False\n",
    "        while done is False:\n",
    "            status, done = downloader.next_chunk()\n",
    "            print(f\"Download {int(status.progress() * 100)}.\")\n",
    "\n",
    "    except HttpError as error:\n",
    "        print(f\"An error occurred: {error}\")\n",
    "        file = None\n",
    "    filepath = os.path.join(os.getcwd(), \"requests\", EXPERIMENT_NAME, filename)\n",
    "    with open(filepath, \"wb\") as outfile:\n",
    "        # Copy the BytesIO stream to the output file\n",
    "        outfile.write(file.getbuffer())\n",
    "\n",
    "    return print(file.getvalue())\n",
    "\n",
    "\n",
    "def download_all_files(creds, EXPERIMENT_NAME):\n",
    "    for file in retrive_forms_data(creds):\n",
    "        download_request_file(file[0][\"fileId\"], file[0][\"fileName\"], creds, EXPERIMENT_NAME)\n",
    "\n",
    "\n",
    "##########\n",
    "## main ##\n",
    "##########\n",
    "def main() -> None:\n",
    "    EXPERIMENT_NAME = input(\"enter EXPERIMENT_NAME:\")\n",
    "    creating_dirs(EXPERIMENT_NAME)\n",
    "    # retrive_forms_data()\n",
    "    creds = google_auth()\n",
    "    download_all_files(creds, EXPERIMENT_NAME)\n",
    "    print(\"downloads finished\")\n",
    "    return EXPERIMENT_NAME"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "61088af9",
   "metadata": {},
   "outputs": [],
   "source": [
    "#####################################\n",
    "#### EXPORTING EMAILS FROM FORMS ####\n",
    "#####################################\n",
    "\n",
    "import re  \n",
    "import json\n",
    "\n",
    "def get_emails_data():\n",
    "    creds = google_auth()\n",
    "\n",
    "    service = discovery.build(\n",
    "        \"forms\",\n",
    "        \"v1\",\n",
    "        http=creds.authorize(Http()),\n",
    "        discoveryServiceUrl=DISCOVERY_DOC,\n",
    "        static_discovery=False,\n",
    "    )\n",
    "\n",
    "    form_id = \"1bVGyD-pz5w3BXM48yHWnhEDVnYNVgzRrF3ysvjAbqHQ\"\n",
    "    result = service.forms().responses().list(formId=form_id).execute()\n",
    "#     print(json.dumps(result, indent=2))\n",
    "    \n",
    "    return result\n",
    "\n",
    "def remove_duplicate_emails(response_str):\n",
    "    response_dict = json.loads(response_str) # Преобразование JSON-строки в Python-объект\n",
    "    email_set = set()\n",
    "\n",
    "    for response in response_dict['responses']:\n",
    "        email = response.get('respondentEmail', None)\n",
    "        if email:\n",
    "            email_set.add(email)\n",
    "\n",
    "    email_list = list(email_set)\n",
    "    return email_list\n",
    "\n",
    "regex = re.compile(r'([A-Za-z0-9]+[.-_])*[A-Za-z0-9\\-]+@[A-Za-z0-9-]+(\\.[A-Z|a-z]{2,})+')  \n",
    "  \n",
    "def emailValid(unique_emails):\n",
    "    for item in unique_emails:\n",
    "        if re.fullmatch(regex, item):\n",
    "            print(item, \"The given mail is valid\")  \n",
    "        else:  \n",
    "            print(item, \"The given mail is invalid\")  \n",
    "            unique_emails.remove(item)\n",
    "    return unique_emails\n",
    "\n",
    "def create_file_with_emails():\n",
    "    # Использования функции\n",
    "    result = get_emails_data()\n",
    "    response_str = json.dumps(result, indent=2)\n",
    "    unique_emails = remove_duplicate_emails(response_str)\n",
    "    unique_emails = emailValid(unique_emails)\n",
    "\n",
    "    # write to file\n",
    "    with open('unique_emails.txt', 'w') as f:\n",
    "        for email in unique_emails:\n",
    "            f.write(f\"{email}\\n\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "47d50764",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "auth token already exists\n",
      "herr.romanoff@gmail.com The given mail is valid\n",
      "kuzminajk2000@gmail.com The given mail is valid\n",
      "thejuzzeppe@gmail.com The given mail is valid\n",
      "olegteravolt@gmail.com The given mail is valid\n"
     ]
    }
   ],
   "source": [
    "create_file_with_emails()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b4fbd077",
   "metadata": {},
   "outputs": [],
   "source": [
    "def combined_pipeline():\n",
    "    EXPERIMENT_NAME = main()\n",
    "    print(EXPERIMENT_NAME)\n",
    "    dfs_list=process_files(EXPERIMENT_NAME)\n",
    "    export_to_input_files(dfs_list, EXPERIMENT_NAME)\n",
    "combined_pipeline()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "id": "79e0abc0",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'herr.romanoff@gmail.com',\n",
       " 'kuzmina-je@sysbiomed.ru',\n",
       " 'kuzmina_je@sysbiomedl.ru',\n",
       " 'kuzminajk2000@gmail.com',\n",
       " 'olegteravolt@gmail.com',\n",
       " 'orcfire658@gmail.com',\n",
       " 'razor1710@mail.ru',\n",
       " 'thejuzzeppe@gmail.com',\n",
       " 'тест'}"
      ]
     },
     "execution_count": 37,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "unique_emails"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "2f3e631d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "orcfire658@gmail.com The given mail is valid\n",
      "thejuzzeppe@gmail.com The given mail is valid\n",
      "kuzminajk2000@gmail.com The given mail is valid\n",
      "kuzmina-je@sysbiomed.ru The given mail is valid\n",
      "тест The given mail is invalid\n",
      "herr.romanoff@gmail.com The given mail is valid\n",
      "olegteravolt@gmail.com The given mail is valid\n",
      "kuzmina_je@sysbiomedl.ru The given mail is valid\n",
      "razor1710@mail.ru The given mail is valid\n"
     ]
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "599c6bac",
   "metadata": {},
   "outputs": [],
   "source": [
    "# !jupyter labextension install @jupyterlab/dataregistry-extension"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5f58e4a1",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3279b389",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8a38c79d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "891b0bfb",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "499e7b66",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
